CREATE TABLE hospital (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    address VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'enabled',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (status IN ('enabled', 'disabled'))
);

CREATE TABLE campus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    hospital_id BIGINT NOT NULL REFERENCES hospital(id),
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'enabled',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (hospital_id, code),
    CHECK (status IN ('enabled', 'disabled'))
);

CREATE TABLE building (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    campus_id BIGINT NOT NULL REFERENCES campus(id),
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'enabled',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (campus_id, code),
    UNIQUE (id, campus_id),
    CHECK (status IN ('enabled', 'disabled'))
);

CREATE TABLE floor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    building_id BIGINT NOT NULL REFERENCES building(id),
    code VARCHAR(20) NOT NULL,
    name VARCHAR(50) NOT NULL,
    level_no INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'enabled',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (building_id, code),
    UNIQUE (id, building_id),
    CHECK (status IN ('enabled', 'disabled'))
);

CREATE TABLE floor_map_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    floor_id BIGINT NOT NULL REFERENCES floor(id),
    revision_no INTEGER NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    image_width INTEGER NOT NULL,
    image_height INTEGER NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (floor_id, revision_no),
    UNIQUE (id, floor_id),
    CHECK (revision_no > 0),
    CHECK (image_width > 0),
    CHECK (image_height > 0)
);

CREATE TABLE building_map_release (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    building_id BIGINT NOT NULL REFERENCES building(id),
    code VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    content_revision BIGINT NOT NULL DEFAULT 0,
    based_on_release_id BIGINT,
    description VARCHAR(500),
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_by VARCHAR(100),
    published_at TIMESTAMP WITH TIME ZONE,
    validated_revision BIGINT,
    validation_passed BOOLEAN,
    last_validated_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (building_id, code),
    UNIQUE (id, building_id),
    FOREIGN KEY (based_on_release_id, building_id)
        REFERENCES building_map_release(id, building_id),
    CHECK (status IN ('draft', 'published', 'retired')),
    CHECK (content_revision >= 0),
    CHECK (NOT is_active OR status = 'published'),
    CHECK (
        status <> 'published'
        OR (published_at IS NOT NULL AND published_by IS NOT NULL)
    )
);

CREATE TABLE release_floor_map (
    release_id BIGINT NOT NULL,
    building_id BIGINT NOT NULL,
    floor_id BIGINT NOT NULL,
    floor_map_revision_id BIGINT NOT NULL,
    PRIMARY KEY (release_id, floor_id),
    FOREIGN KEY (release_id, building_id)
        REFERENCES building_map_release(id, building_id),
    FOREIGN KEY (floor_id, building_id)
        REFERENCES floor(id, building_id),
    FOREIGN KEY (floor_map_revision_id, floor_id)
        REFERENCES floor_map_revision(id, floor_id)
);

CREATE INDEX idx_release_building_status
    ON building_map_release(building_id, status);
