CREATE TABLE path_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id BIGINT NOT NULL,
    floor_id BIGINT NOT NULL,
    public_id UUID NOT NULL,
    code VARCHAR(80) NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    node_type VARCHAR(30) NOT NULL DEFAULT 'normal',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    remark VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (release_id, floor_id)
        REFERENCES release_floor_map(release_id, floor_id),
    UNIQUE (release_id, public_id),
    UNIQUE (release_id, code),
    UNIQUE (id, release_id),
    UNIQUE (id, release_id, floor_id),
    CHECK (x >= 0),
    CHECK (y >= 0)
);

CREATE TABLE path_edge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id BIGINT NOT NULL,
    floor_id BIGINT NOT NULL,
    public_id UUID NOT NULL,
    code VARCHAR(80) NOT NULL,
    from_node_id BIGINT NOT NULL,
    to_node_id BIGINT NOT NULL,
    time_seconds INTEGER NOT NULL,
    distance_meters NUMERIC(10, 2) NOT NULL,
    direction VARCHAR(20) NOT NULL DEFAULT 'both',
    edge_type VARCHAR(30) NOT NULL DEFAULT 'walk',
    access_scope VARCHAR(20) NOT NULL DEFAULT 'public',
    accessible BOOLEAN NOT NULL DEFAULT TRUE,
    base_status VARCHAR(20) NOT NULL DEFAULT 'enabled',
    remark VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (release_id, floor_id)
        REFERENCES release_floor_map(release_id, floor_id),
    FOREIGN KEY (from_node_id, release_id, floor_id)
        REFERENCES path_node(id, release_id, floor_id),
    FOREIGN KEY (to_node_id, release_id, floor_id)
        REFERENCES path_node(id, release_id, floor_id),
    UNIQUE (release_id, public_id),
    UNIQUE (release_id, code),
    UNIQUE (id, release_id),
    CHECK (from_node_id <> to_node_id),
    CHECK (time_seconds > 0),
    CHECK (distance_meters >= 0),
    CHECK (direction IN ('forward', 'both')),
    CHECK (edge_type IN ('walk', 'corridor', 'door', 'ramp', 'virtual')),
    CHECK (access_scope IN ('public', 'staff')),
    CHECK (base_status IN ('enabled', 'disabled'))
);

CREATE TABLE poi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id BIGINT NOT NULL,
    floor_id BIGINT NOT NULL,
    public_id UUID NOT NULL,
    code VARCHAR(80) NOT NULL,
    node_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    access_scope VARCHAR(20) NOT NULL DEFAULT 'public',
    accessible BOOLEAN NOT NULL DEFAULT TRUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    remark VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (release_id, floor_id)
        REFERENCES release_floor_map(release_id, floor_id),
    FOREIGN KEY (node_id, release_id, floor_id)
        REFERENCES path_node(id, release_id, floor_id),
    UNIQUE (release_id, public_id),
    UNIQUE (release_id, code),
    UNIQUE (id, release_id),
    CHECK (x >= 0),
    CHECK (y >= 0),
    CHECK (access_scope IN ('public', 'staff'))
);

CREATE TABLE poi_keyword (
    poi_id BIGINT NOT NULL,
    release_id BIGINT NOT NULL,
    keyword VARCHAR(100) NOT NULL,
    PRIMARY KEY (poi_id, keyword),
    FOREIGN KEY (poi_id, release_id)
        REFERENCES poi(id, release_id)
);

CREATE INDEX idx_node_release_floor
    ON path_node(release_id, floor_id);
CREATE INDEX idx_edge_release_floor
    ON path_edge(release_id, floor_id);
CREATE INDEX idx_edge_release_from
    ON path_edge(release_id, from_node_id);
CREATE INDEX idx_edge_release_to
    ON path_edge(release_id, to_node_id);
CREATE INDEX idx_poi_release_floor
    ON poi(release_id, floor_id);
CREATE INDEX idx_poi_keyword_value
    ON poi_keyword(keyword);
