CREATE TABLE vertical_connector (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id BIGINT NOT NULL REFERENCES building_map_release(id),
    public_id UUID NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(100) NOT NULL,
    connector_type VARCHAR(30) NOT NULL,
    access_scope VARCHAR(20) NOT NULL DEFAULT 'public',
    accessible BOOLEAN NOT NULL DEFAULT TRUE,
    base_status VARCHAR(20) NOT NULL DEFAULT 'enabled',
    remark VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (release_id, public_id),
    UNIQUE (release_id, code),
    UNIQUE (id, release_id),
    CHECK (connector_type IN ('elevator', 'stairs')),
    CHECK (access_scope IN ('public', 'staff')),
    CHECK (base_status IN ('enabled', 'disabled'))
);

CREATE TABLE connector_stop (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id BIGINT NOT NULL,
    connector_id BIGINT NOT NULL,
    floor_id BIGINT NOT NULL,
    node_id BIGINT NOT NULL,
    public_id UUID NOT NULL,
    stop_code VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (connector_id, release_id)
        REFERENCES vertical_connector(id, release_id),
    FOREIGN KEY (node_id, release_id, floor_id)
        REFERENCES path_node(id, release_id, floor_id),
    UNIQUE (release_id, public_id),
    UNIQUE (release_id, stop_code),
    UNIQUE (connector_id, floor_id),
    UNIQUE (id, release_id, connector_id),
    UNIQUE (id, release_id),
    CHECK (connector_id IS NOT NULL)
);

CREATE TABLE vertical_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id BIGINT NOT NULL,
    connector_id BIGINT NOT NULL,
    public_id UUID NOT NULL,
    code VARCHAR(80) NOT NULL,
    from_stop_id BIGINT NOT NULL,
    to_stop_id BIGINT NOT NULL,
    time_seconds INTEGER NOT NULL,
    distance_meters NUMERIC(10, 2) NOT NULL DEFAULT 0,
    direction VARCHAR(20) NOT NULL DEFAULT 'both',
    access_scope VARCHAR(20) NOT NULL DEFAULT 'public',
    accessible BOOLEAN NOT NULL DEFAULT TRUE,
    base_status VARCHAR(20) NOT NULL DEFAULT 'enabled',
    remark VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (connector_id, release_id)
        REFERENCES vertical_connector(id, release_id),
    FOREIGN KEY (from_stop_id, release_id, connector_id)
        REFERENCES connector_stop(id, release_id, connector_id),
    FOREIGN KEY (to_stop_id, release_id, connector_id)
        REFERENCES connector_stop(id, release_id, connector_id),
    UNIQUE (release_id, public_id),
    UNIQUE (release_id, code),
    UNIQUE (id, release_id),
    CHECK (from_stop_id <> to_stop_id),
    CHECK (time_seconds > 0),
    CHECK (distance_meters >= 0),
    CHECK (direction IN ('forward', 'both')),
    CHECK (access_scope IN ('public', 'staff')),
    CHECK (base_status IN ('enabled', 'disabled'))
);

CREATE TABLE edge_state_override (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    building_id BIGINT NOT NULL,
    release_id BIGINT NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    path_edge_id BIGINT,
    vertical_link_id BIGINT,
    vertical_connector_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'closed',
    effective_from TIMESTAMP WITH TIME ZONE NOT NULL,
    effective_to TIMESTAMP WITH TIME ZONE,
    reason VARCHAR(500) NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_by VARCHAR(100),
    revoked_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (release_id, building_id)
        REFERENCES building_map_release(id, building_id),
    FOREIGN KEY (path_edge_id, release_id)
        REFERENCES path_edge(id, release_id),
    FOREIGN KEY (vertical_link_id, release_id)
        REFERENCES vertical_link(id, release_id),
    FOREIGN KEY (vertical_connector_id, release_id)
        REFERENCES vertical_connector(id, release_id),
    CHECK (target_type IN ('path_edge', 'vertical_link', 'vertical_connector')),
    CHECK (status = 'closed'),
    CHECK (effective_to IS NULL OR effective_to > effective_from)
);

CREATE TABLE release_validation_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id BIGINT NOT NULL REFERENCES building_map_release(id),
    content_revision BIGINT NOT NULL,
    passed BOOLEAN NOT NULL,
    result_text TEXT NOT NULL,
    checked_by VARCHAR(100) NOT NULL,
    checked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (content_revision >= 0)
);

CREATE TABLE building_release_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id BIGINT NOT NULL REFERENCES building(id),
    from_release_id BIGINT,
    to_release_id BIGINT NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    operated_by VARCHAR(100) NOT NULL,
    reason VARCHAR(500),
    operated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (from_release_id, building_id)
        REFERENCES building_map_release(id, building_id),
    FOREIGN KEY (to_release_id, building_id)
        REFERENCES building_map_release(id, building_id),
    CHECK (event_type IN ('publish', 'rollback'))
);

CREATE INDEX idx_stop_release_floor
    ON connector_stop(release_id, floor_id);
CREATE INDEX idx_link_release_connector
    ON vertical_link(release_id, connector_id);
CREATE INDEX idx_override_release_window
    ON edge_state_override(release_id, revoked_at, effective_from, effective_to);
