CREATE TABLE building_route_regression_config (
    building_id BIGINT PRIMARY KEY REFERENCES building(id),
    revision BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (revision >= 0)
);

INSERT INTO building_route_regression_config (building_id, revision)
SELECT id, 0
FROM building;

ALTER TABLE building_map_release
    ADD COLUMN validated_route_regression_revision BIGINT;

ALTER TABLE release_validation_run
    ADD COLUMN route_regression_revision BIGINT NOT NULL DEFAULT 0;

CREATE TABLE building_route_regression_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    building_id BIGINT NOT NULL REFERENCES building(id),
    code VARCHAR(80) NOT NULL,
    name VARCHAR(120) NOT NULL,
    start_poi_code VARCHAR(80) NOT NULL,
    end_poi_code VARCHAR(80) NOT NULL,
    route_mode VARCHAR(30) NOT NULL DEFAULT 'normal',
    critical BOOLEAN NOT NULL DEFAULT TRUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    max_distance_meters NUMERIC(10, 2),
    max_estimated_seconds INTEGER,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (building_id, code),
    CHECK (start_poi_code <> end_poi_code),
    CHECK (route_mode IN ('normal', 'accessible')),
    CHECK (
        max_distance_meters IS NULL
        OR max_distance_meters > 0
    ),
    CHECK (
        max_estimated_seconds IS NULL
        OR max_estimated_seconds > 0
    )
);

CREATE INDEX idx_route_regression_building_enabled
    ON building_route_regression_case(building_id, enabled);

INSERT INTO building_route_regression_case (
    id,
    public_id,
    building_id,
    code,
    name,
    start_poi_code,
    end_poi_code,
    route_mode,
    critical,
    enabled,
    max_distance_meters,
    max_estimated_seconds,
    created_by,
    updated_by
) VALUES
    (
        7001,
        '00000000-0000-0000-0000-000000007001',
        1200,
        'ENTRANCE-TO-SERVICE',
        '入口到门诊服务台',
        'P-ENTRANCE',
        'P-REGISTRATION',
        'normal',
        TRUE,
        TRUE,
        100,
        180,
        'fixture',
        'fixture'
    ),
    (
        7002,
        '00000000-0000-0000-0000-000000007002',
        1200,
        'ENTRANCE-TO-LAB',
        '入口到二层检验科',
        'P-ENTRANCE',
        'P-LAB-2F',
        'normal',
        TRUE,
        TRUE,
        180,
        300,
        'fixture',
        'fixture'
    ),
    (
        7003,
        '00000000-0000-0000-0000-000000007003',
        1200,
        'ENTRANCE-TO-ULTRASOUND',
        '入口到三层超声医学科',
        'P-ENTRANCE',
        'P-ULTRASOUND-3F',
        'normal',
        TRUE,
        TRUE,
        200,
        300,
        'fixture',
        'fixture'
    ),
    (
        7004,
        '00000000-0000-0000-0000-000000007004',
        1200,
        'ENTRANCE-TO-ULTRASOUND-ACCESSIBLE',
        '入口到三层超声医学科无障碍路线',
        'P-ENTRANCE',
        'P-ULTRASOUND-3F',
        'accessible',
        TRUE,
        TRUE,
        250,
        360,
        'fixture',
        'fixture'
    );
